### PR TITLE
Add the optional ability to dump outgoing http request for debugging …

### PR DESCRIPTION
**Pull request by peachdt**
…purposes.

### CODE REVIEW

**Comment by mozillazg** [comment]
Thank you! BTW, Please change your PR against the `develop` branch, thanks!
@wrunk What do you think about this PR?

IHMO, we can add an option (e.g. `Hook` or `ReqHook`) to deal with these similar cases, like this:

```
Hook func(r *http.Request) (resp *http.Response, err error)

// if resp != nil or err != nil , use this resp and don't send request again.
```
@peachdt @wrunk What do you think about this idea?

**Comment by wrunk** [comment]
I think the hook option would be good. I was also experimenting with httputil.DumpResponse for the response and it seems to very nicely format json responses.

Perhaps we can have a pre and post request hook? When we tried to dump the request after a.Client.Do(req) the body can't be dumped.

Let us know, thanks!

**Comment by mozillazg** [comment]
@wrunk like this?

```
type Hook interface {
  BeforeRequest(r *http.Request) (resp *http.Response, err error)
  AfterRequest(r *http.Request, resp *http.Response, err error) (newResp *http.Response, newErr error)
}

type Args struct {
...
   Hooks []Hook
}
```

**Comment by wrunk** [comment]
I like that. I'm not yet totally familiar with the repo, but have a pretty good idea on how we could implement this. Happy to give it a try, or perhaps I can help write some tests if you would prefer to implement it. LMK, and thanks for the help on this.

**Comment by mozillazg** [comment]
@wrunk Yes, just try it.

**Pull request closed without merging**
